modLoader        = "javafml"
loaderVersion    = "${properties["net.toml.loaderVersion"]}"
license          = "${properties["mod.license"]}"
issueTrackerURL  = "${properties["mod.link.issues"]}"

[[mods]]
modId       = "${properties["mod.id"]}"
version     = "${properties["mod.version"]}+neoforge-${properties["minecraft.version"]}"
displayName = "${properties["mod.name"]}"
description = "${properties["mod.description"]}."
authors     = "${properties["mod.author"]}"
logoFile    = "assets/${properties["mod.id"]}/icon.png"

[[dependencies.${properties["mod.id"]}]]
modId        = "neoforge"
type         = "required"
versionRange = "${properties["neo.toml.dependencies.neoforge"]}"
ordering     = "NONE"
side         = "BOTH"

[[dependencies.${properties["mod.id"]}]]
modId        = "minecraft"
type         = "required"
versionRange = "${properties["neo.toml.dependencies.minecraft"]}"
ordering     = "NONE"
side         = "BOTH"

[[dependencies.${properties["mod.id"]}]]
modId        = "architectury"
type         = "required"
versionRange = "${properties["neo.toml.dependencies.architectury"]}"
ordering     = "AFTER"
side         = "BOTH"

# [[dependencies.${properties["mod.id"]}]]
# modId        = "fabric_api"
# type         = "required"
# versionRange = "[0.115.6,)"
# ordering     = "AFTER"
# side         = "BOTH"
# Edit: 'Forgified Fabric API' is not on the latest version. oops-

# Mixin declarations are dynamically inserted below:
${properties["mixins"]}
